name: fire99
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  provider:
  intl:
  firebase_admob:
  another_flushbar: ^1.10.22
  firebase_core: ^0.5.2
  flutter_native_admob: ^2.1.0+3
  admob_flutter: ^1.0.1
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.4
  firebase_storage: ^5.1.0
  firebase_analytics: ^6.3.0
  image_picker: ^0.6.7+17
  path: ^1.7.0
  animated_text_kit: ^4.2.1
  shared_preferences: ^0.5.12+4
  carousel_pro: ^1.0.0
  android_alarm_manager_plus: ^1.0.1
  ffi: ^1.1.2
  mailer: ^3.3.0
  date_time_picker: ^1.1.1
  flutter_local_notifications: ^4.0.1+2
  awesome_notifications: ^0.0.6+7
  video_player: ^1.0.1
  animations: ^2.0.1
  url_launcher: ^5.7.0
  font_awesome_flutter: ^8.2.0
  google_sign_in:
  flutter_signin_button:
  animated_splash_screen: ^1.1.0
  page_transition:
  flutter_svg_provider:
  flutter_svg:
  share : ^0.6.5
  webview_flutter: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.1"
  flutter_launcher_name: "^0.0.1"

flutter_launcher_name:
    name: "Dealkarma"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/d1.jfif"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
